### ISSUE TITLE
View can't be obtained when ItemClicked.

### ISSUE THREAD

**Issue by caleroalbelo90** [smaugho/declex#28]
When I declared a item_layout with some view like RelativeLayout (id=relDate), and it is called in the @ItemClick annotations from it params:
```
@ItemClick
void horizontalList(final View relDate,DateWeek_ model) {
//Do somethings with relDate and model
}
```
The idea is to modify relDate and it childrens views with info of model, so relDate is not recognized, it is not obtained correctly.

**Comment by smaugho** [comment]
ItemClicked is executed when an Item from the AdapterView (ex. ListView) is clicked, in this case, to get a specific view from there, the method should make a findViewById over the View element in the function, for instance, this is the code generated by this:

```java
@ItemClick
    void lessonsList(Lesson_ model) {
     
    }
```

Generated:

```java
        lessonsList$view.setOnItemClickListener(new OnItemClickListener() {

                @Override
                public void onItemClick(AdapterView<?> parent, View view, int position, long id) {
                    final Lesson_ model = lessonsList.get(position);
                    lessonsList(model);
                }
            }
        );
```

Since this method is not called from within the Adapter, the views cannot be obtained from there... Also, "view" probably holds the ViewHolder, in such case, it would be more efficient to get the view to be injected from there (this can be done if there's no a custom adapter).

This is not a bug, it is an enhancement.

**Comment by smaugho** [comment]
It will be solved calling:

```java
    view.findViewById(R.id.fieldName)
```

from within the onItemClickedListener.
